import Head from "next/head";
import TopNavSocial from "../components/TopNavSocial";
import TopNav from "../components/TopNav";

export default function HomePage() {
  return (
    <div className="">
      <Head>
        <title>IEMLabs-CyberSecurity</title>
        <meta name="description" content="Generated by IEMLabs-CyberSecurity" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <TopNavSocial />
        <TopNav />
        <div className="h-96"></div>
      </main>
    </div>
  );
}
