import Head from "next/head";
import Link from "next/link";
import HomePage from "./homepage";
import Footer from "../components/Footer";

export default function Home() {
  return (
    <div className="w-screen h-screen bg-slate-50">
      <Head>
        <meta name="description" content="Generated by IEMLabs-CyberSecurity" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://unpkg.com/boxicons@2.1.2/css/boxicons.min.css"
          rel="stylesheet"
        />
      </Head>
      <main className="">
        <Link href="/" passHref>
          <HomePage />
        </Link>
      </main>

      <footer className="text-center lg:text-left bg-gray-100 text-gray-600">
        <Footer />
      </footer>
    </div>
  );
}
